//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ContentText { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> ChangedOn { get; set; }
        public string UserId { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
    }
}
