<%@ Page Title="Books" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Books.aspx.cs" Inherits="LibrarySystem.LoggedUser.Books" %>
<asp:Content ID="Content" ContentPlaceHolderID="MainContent" runat="server">
    <span runat ="server" id="storedValue" style="display:none"></span>
     <div class="text-center">
        <asp:Button  runat="server" CssClass="btn" Text="Ok" ID="ConfirmButton" OnClick="ConfirmButton_Click"/>
        <asp:Button  runat="server" CssClass="btn" Text="Cancel" ID="CanselButton" OnClick="CanselButton_Click"/>
     </div>
    <asp:GridView 
        ID="GridViewBooks"
        runat="server" 
        AllowPaging="true" EnableViewState="false" 
        AllowSorting="true" PageSize="3" 
        ItemType="LibrarySystem.Models.Book"
        DataKeyNames="Id" SelectMethod="GridViewBooks_GetData" UpdateMethod="GridViewBooks_UpdateItem" DeleteMethod="GridViewBooks_DeleteItem"
        AutoGenerateColumns="false" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" >

        <Columns>

            <asp:TemplateField HeaderText="Title" SortExpression="Title">
                <ItemTemplate>
                    <p><%#: (Item.Title.Length > 20 ? ((Item.Title.Substring(0, 19) + "...")) : Item.Title) %></p>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Author" SortExpression="Author">
                <ItemTemplate>
                    
                     <p ><%#: (Item.Author != null && Item.Author.Length > 20 ? ((Item.Author.Substring(0, 19) + "...")) : Item.Author) %></p>
                </ItemTemplate>
                
                 <EditItemTemplate>
                     <asp:TextBox runat="server" Text="<%# Item.Author %>"></asp:TextBox>
                 </EditItemTemplate>
            </asp:TemplateField>
             <asp:TemplateField HeaderText="ISBN" SortExpression="ISBN">
                <ItemTemplate>
                    
                      <p ><%#: (Item.ISBN != null && Item.ISBN.Length > 20 ? ((Item.ISBN.Substring(0, 19) + "...")) : Item.ISBN) %></p>
                </ItemTemplate>
                
                 <EditItemTemplate>
                     <asp:TextBox runat="server" Text="<%# Item.ISBN %>"></asp:TextBox>
                 </EditItemTemplate>
            </asp:TemplateField>
             <asp:TemplateField HeaderText="WebSite" SortExpression="WebSite">
                <ItemTemplate>
                    
                     <a href="<%# Item.WebSite %>"><%#: (Item.WebSite != null && Item.WebSite.Length > 20 ? ((Item.WebSite.Substring(0, 19) + "...")) : Item.WebSite) %></a>
                </ItemTemplate>
                
                 <EditItemTemplate>
                     <asp:TextBox runat="server" Text="<%# Item.WebSite %>"></asp:TextBox>
                 </EditItemTemplate>
            </asp:TemplateField>
            
            <asp:TemplateField  HeaderText="Category Title">
                <ItemTemplate>
                    <p ><%#: (Item.Category.Title != null && Item.Category.Title.Length > 20 ? ((Item.Category.Title.Substring(0, 19) + "...")) : Item.Category.Title) %></p>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:DropDownList 
                        runat="server" ID="CategoriesDDL"
                        SelectMethod="GridViewEditCategories_GetData" DataTextField="Title"
                            DataValueField="Id"
                            SelectedValue='<%# BindItem.CategoryId %>'>

                    </asp:DropDownList> 
                </EditItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField  HeaderText="Description">
                <ItemTemplate>
                   <p>Available for edit only</p>
                </ItemTemplate>
               <EditItemTemplate>
                     <asp:TextBox runat="server" Text="<%# Item.Description %>"></asp:TextBox>
                 </EditItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
  
     <asp:LinkButton CssClass="btn-link" Text="Create new" runat="server" id="CreateBook" OnClick="CreateBook_Click"/> 

    <asp:Panel ID="CreateNewBookForm" runat="server" Visible="false">
        <h2>Create New Book</h2>
        <label for="BookTitle" class="col-lg-2 control-label">Title: </label>
        <div class="col-lg-10">
            <input type="text" runat="server" class="form-control" id="BookTitle" placeholder="Enter book title ...">
             <asp:RequiredFieldValidator
                 ValidationGroup="NewBookValidation" CssClass="text-error"
                 runat="server" 
                 ControlToValidate="BookTitle" 
                 ErrorMessage="The Field Title is required.<br/>"/>
        </div>
       
         <label for="BookAuthor" class="col-lg-2 control-label">Author(s): </label>
        <div class="col-lg-10">
            <input type="text" runat="server" class="form-control" id="BookAuthor" placeholder="Enter book author/ authors ...">
             <asp:RequiredFieldValidator 
                 ValidationGroup="NewBookValidation" CssClass="text-error"
                 runat="server" 
                 ControlToValidate="BookAuthor" 
                 ErrorMessage="The Field Author is required.<br/>"/>
        </div>

        <label for="BookISBN" class="col-lg-2 control-label">ISBN: </label>
        <div class="col-lg-10">
            <input type="text" runat="server" class="form-control" id="BookISBN" placeholder="Enter book ISBN ...">
        </div>

         <label for="BookWebSite" class="col-lg-2 control-label">Web site: </label>
        <div class="col-lg-10">
            <input type="text" runat="server" class="form-control" id="BookWebSite" placeholder="Enter book web site ...">
        </div>

   
        <label for="BookDescription" class="col-lg-2 control-label">Description: </label>
        <div class="col-lg-10">
            <textarea runat="server" class="form-control" id="BookDescription" rows="6" placeholder="Enter book description ..." ></textarea>
        </div>


        <label for="NewBookCategory" class="col-lg-2 control-label">Category: </label>
        <div class="col-lg-10">
             <asp:DropDownList 
                        runat="server" ID="CategoriesDDLNewBook"
                        SelectMethod="GridViewEditCategories_GetData" DataTextField="Title"
                            DataValueField="Id">

                    </asp:DropDownList> 
        </div>

        <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <asp:Button CssClass="btn btn-default" runat="server" ID="SubmitBookCreation" Text="Ok" CausesValidation="true" ValidationGroup="NewBookValidation"  OnClick="SubmitBookCreation_Click" />
            <asp:Button CssClass="btn btn-default" runat="server" ID="CancelBookCreation" Text="Cancel" OnClick="CancelBookCreation_Click"  />  
        </div>
        </div>
    </asp:Panel>

    
</asp:Content>
